from typing import Protocol


class UserRepository(Protocol):
    def get(self, user_id: str) -> dict | None: ...
    def find_by_email(self, email: str) -> dict | None: ...
    def find_by_reset_token_hash(self, token_hash: str) -> dict | None: ...
    def create(self, doc: dict) -> dict: ...
    def update(self, doc: dict) -> dict: ...
    def delete(self, user_id: str) -> None: ...
    def list_by_role(self, role: str) -> list[dict]: ...
    def count_by_role(self, role: str) -> int: ...


class ProviderRepository(Protocol):
    def get(self, provider_id: str) -> dict | None: ...
    def find_by_user_id(self, user_id: str) -> dict | None: ...
    def create(self, doc: dict) -> dict: ...
    def update(self, doc: dict) -> dict: ...
    def delete(self, provider_id: str) -> None: ...
    def list_public(
        self, search: str | None, category_id: str | None, sort: str, offset: int, limit: int
    ) -> tuple[list[dict], int]: ...
    def list_featured(self, limit: int) -> list[dict]: ...
    def list_admin(self, status: str | None) -> list[dict]: ...
    def count_by_status(self, status: str) -> int: ...
    def count_by_category(self, category_id: str) -> int: ...
    def category_usage_counts(self) -> dict[str, int]: ...
    def increment_whatsapp_clicks(self, provider_id: str) -> None: ...


class ReviewRepository(Protocol):
    def get(self, review_id: str, provider_id: str) -> dict | None: ...
    def find_by_user_and_provider(self, user_id: str, provider_id: str) -> dict | None: ...
    def create(self, doc: dict) -> dict: ...
    def update(self, doc: dict) -> dict: ...
    def delete(self, review_id: str, provider_id: str) -> None: ...
    def list_by_provider(self, provider_id: str) -> list[dict]: ...
    def list_by_user(self, user_id: str) -> list[dict]: ...
    def list_all(self) -> list[dict]: ...
    def delete_by_provider(self, provider_id: str) -> None: ...
    def aggregate_for_provider(self, provider_id: str) -> tuple[int, float]: ...
    def count_all(self) -> int: ...


class CategoryRepository(Protocol):
    def get(self, category_id: str) -> dict | None: ...
    def create(self, doc: dict) -> dict: ...
    def update(self, doc: dict) -> dict: ...
    def delete(self, category_id: str) -> None: ...
    def list_active(self) -> list[dict]: ...
    def list_all(self) -> list[dict]: ...


class PhotoStorage(Protocol):
    def upload(self, blob_name: str, data: bytes, content_type: str) -> str: ...
    def delete(self, blob_name: str) -> None: ...


class EmailService(Protocol):
    def send(self, to: str, subject: str, html: str) -> None: ...


class Geocoder(Protocol):
    def geocode(self, rua: str, numero: str, bairro: str) -> dict | None: ...


class AiSearchService(Protocol):
    def search(self, question: str) -> dict:
        """Retorna {'answer': str, 'providers': list[dict]} para uma pergunta em linguagem natural."""
        ...


class DuplicateReviewError(Exception):
    pass
